<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Order Number ORD-1734533476015</name>
   <tag></tag>
   <elementGuidId>329effb4-4e29-4976-95ac-d5817be8715d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.font-semibold.text-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6f8bc27c-3baa-4905-9a62-b6816c86dd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-lg</value>
      <webElementGuid>160d8837-118c-429d-8788-6898df894d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Number: ORD-1734533476015</value>
      <webElementGuid>1577817d-2225-4a13-bf00-8fba4dd5290e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dark:bg-neutral-900 bg-white text-black dark:text-white&quot;]/div[@class=&quot;container mx-auto p-4 min-h-screen&quot;]/div[@class=&quot;border rounded-lg shadow-md p-4 mb-6 bg-white&quot;]/div[@class=&quot;mb-4&quot;]/p[@class=&quot;font-semibold text-lg&quot;]</value>
      <webElementGuid>55e37363-c043-4838-a51f-aa5f87cdc618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/p</value>
      <webElementGuid>ecd7be98-1a47-4b28-85cf-655e88953a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Orders'])[1]/following::p[1]</value>
      <webElementGuid>b18dc6c2-8f41-4b29-9a63-6e5539aba299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[1]/preceding::p[2]</value>
      <webElementGuid>6ca5f41e-de24-4674-8acf-45e9c4ee0e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order Number:']/parent::*</value>
      <webElementGuid>6238a9f7-8f2e-4d50-bb0b-3aed1bf16605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>071e6550-717b-41c9-8776-71299d43c6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Order Number: ORD-1734533476015' or . = 'Order Number: ORD-1734533476015')]</value>
      <webElementGuid>a7f5fee3-64e2-4f39-afda-d7fdd918686a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
