<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test</name>
   <tag></tag>
   <elementGuidId>41806fff-b10d-40be-8d05-9fd5d515f661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14f9ff52-abb1-4791-a489-2898c4641979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-3 p-3 hover:bg-gray-100 cursor-pointer</value>
      <webElementGuid>42a220a5-93bc-4601-b54c-da8d2bb37c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>4eb8132d-0274-47de-a618-c009ef687264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dark:bg-neutral-900 bg-white text-black dark:text-white&quot;]/div[@class=&quot;card flex items-center justify-between p-3 border-b-2 dark:border-neutral-800&quot;]/div[@class=&quot;relative flex-grow mx-1 md:mx-4&quot;]/div[@class=&quot;absolute z-50 bg-gray-200 border rounded-lg shadow-lg mt-2 w-full max-h-60 overflow-y-auto&quot;]/div[@class=&quot;flex items-center gap-3 p-3 hover:bg-gray-100 cursor-pointer&quot;]</value>
      <webElementGuid>92e64ba6-3c37-45f9-8c59-8e57c25edb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>024dbde2-56f6-41a8-b508-218444e78e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aidd Tools'])[1]/following::div[3]</value>
      <webElementGuid>23fde43d-72ed-4b6d-950b-c453175d4b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[2]/preceding::div[1]</value>
      <webElementGuid>ac1918bc-d52d-4a95-8de9-a3b2dea7762e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>2aaaf462-3229-4435-87ce-a5d906ce319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>6a2cc236-e738-4400-a02a-c9e66b9348e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
