<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Test</name>
   <tag></tag>
   <elementGuidId>9b4c361b-e129-40ee-b251-66042c03efcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.text-3xl.font-bold.text-gray-900.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>98b45a6d-7955-4239-bbd1-485a68d4d870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl font-bold text-gray-900 mb-2</value>
      <webElementGuid>9291ca1a-91b6-40e7-872d-bfbbd5401de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>e3d57568-2775-4830-ac98-7f775db0faa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dark:bg-neutral-900 bg-white text-black dark:text-white&quot;]/div[@class=&quot;min-h-screen bg-gradient-to-br from-gray-100 via-white to-gray-50 p-6&quot;]/div[@class=&quot;max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10 bg-white bg-opacity-90 shadow-xl backdrop-blur-md rounded-2xl overflow-hidden&quot;]/div[@class=&quot;flex flex-col justify-between p-8&quot;]/div[1]/h2[@class=&quot;text-3xl font-bold text-gray-900 mb-2&quot;]</value>
      <webElementGuid>3ece0aef-e493-46ca-94fd-b25183534245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/h2</value>
      <webElementGuid>cba6e657-8929-45d0-8b95-73e92b07650d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Details'])[1]/following::h2[1]</value>
      <webElementGuid>949f281b-193e-4836-b858-15712cfcaebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specifications'])[1]/preceding::h2[1]</value>
      <webElementGuid>309a79cc-915e-4530-98a5-bcbd643b2e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP 94.00'])[1]/preceding::h2[1]</value>
      <webElementGuid>b3e4f87a-2235-43c4-be64-a509c32cd4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test']/parent::*</value>
      <webElementGuid>c4e61ad1-8f6e-48b3-b237-9b0500e9f243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>04ed8f0d-7642-44de-ad3e-f9d638292edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>321e5e87-1716-48dc-9aa8-db9b34a8f13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
