<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>fff9726a-9756-461a-a21a-45c779e6ffd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r7:']/div[2]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9af87915-c7f0-44cd-9827-9fd1a820abd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accept.paymobsolutions.com/api/acceptance/iframes/884013?payment_token=ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hPRGMxTURBMUxDSmhiVzkxYm5SZlkyVnVkSE1pT2pJd05qQXdMQ0pqZFhKeVpXNWplU0k2SWtWSFVDSXNJbWx1ZEdWbmNtRjBhVzl1WDJsa0lqbzBPRGcyT0RFMExDSnZjbVJsY2w5cFpDSTZNamMxT0RNNE1UVXpMQ0ppYVd4c2FXNW5YMlJoZEdFaU9uc2labWx5YzNSZmJtRnRaU0k2SWtGc2FTSXNJbXhoYzNSZmJtRnRaU0k2SWtGb2JXVmtJaXdpYzNSeVpXVjBJam9pTnpJaUxDSmlkV2xzWkdsdVp5STZJamt3TVRnaUxDSm1iRzl2Y2lJNklqTWlMQ0poY0dGeWRHMWxiblFpT2lJMklpd2lZMmwwZVNJNkltMXZhMnRoZEcwaUxDSnpkR0YwWlNJNkltTmhhWEp2SWl3aVkyOTFiblJ5ZVNJNkltVm5lWEIwSWl3aVpXMWhhV3dpT2lKcmFYSnlZV0UyT1RsQVoyMWhhV3d1WTI5dElpd2ljR2h2Ym1WZmJuVnRZbVZ5SWpvaU1qQXhNREl6TXpBME5UQTBJaXdpY0c5emRHRnNYMk52WkdVaU9pSXhNVFUzTVNJc0ltVjRkSEpoWDJSbGMyTnlhWEIwYVc5dUlqb2lUa0VpZlN3aWJHOWphMTl2Y21SbGNsOTNhR1Z1WDNCaGFXUWlPbVpoYkhObExDSmxlSFJ5WVNJNmUzMHNJbk5wYm1kc1pWOXdZWGx0Wlc1MFgyRjBkR1Z0Y0hRaU9tWmhiSE5sTENKd2JXdGZhWEFpT2lJME5DNHlNRFF1TnpndU1UQTRJbjAud1Nwd3d6ZFQzXzNlNVJfX0NvTDVwSkE2dlJoeGhYc05fMFZGREQ5TmQ4TUZUb2Y3V0VKNzhLbXdEWWtaSHhhb2dPa3hCaU5McEdxU0dlN3RKcGlmaFE=</value>
      <webElementGuid>7caf6f78-bb01-4223-a29b-7fa65bdfb64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>017c2ad9-e056-4ed9-b6a9-8de87b194339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600px</value>
      <webElementGuid>734c311f-9292-47c7-9194-9e9eaf76a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c59d16fb-36c4-4372-8fc4-168b4310e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r7:&quot;)/div[@class=&quot;mt-4 w-full&quot;]/iframe[1]</value>
      <webElementGuid>9d682ef4-f527-43cb-a786-9c67933697a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r7:']/div[2]/iframe</value>
      <webElementGuid>94af9d44-4c18-4b1b-96e3-c7a08be175b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>322c3f7a-4c02-475c-a345-b4036f481bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accept.paymobsolutions.com/api/acceptance/iframes/884013?payment_token=ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hPRGMxTURBMUxDSmhiVzkxYm5SZlkyVnVkSE1pT2pJd05qQXdMQ0pqZFhKeVpXNWplU0k2SWtWSFVDSXNJbWx1ZEdWbmNtRjBhVzl1WDJsa0lqbzBPRGcyT0RFMExDSnZjbVJsY2w5cFpDSTZNamMxT0RNNE1UVXpMQ0ppYVd4c2FXNW5YMlJoZEdFaU9uc2labWx5YzNSZmJtRnRaU0k2SWtGc2FTSXNJbXhoYzNSZmJtRnRaU0k2SWtGb2JXVmtJaXdpYzNSeVpXVjBJam9pTnpJaUxDSmlkV2xzWkdsdVp5STZJamt3TVRnaUxDSm1iRzl2Y2lJNklqTWlMQ0poY0dGeWRHMWxiblFpT2lJMklpd2lZMmwwZVNJNkltMXZhMnRoZEcwaUxDSnpkR0YwWlNJNkltTmhhWEp2SWl3aVkyOTFiblJ5ZVNJNkltVm5lWEIwSWl3aVpXMWhhV3dpT2lKcmFYSnlZV0UyT1RsQVoyMWhhV3d1WTI5dElpd2ljR2h2Ym1WZmJuVnRZbVZ5SWpvaU1qQXhNREl6TXpBME5UQTBJaXdpY0c5emRHRnNYMk52WkdVaU9pSXhNVFUzTVNJc0ltVjRkSEpoWDJSbGMyTnlhWEIwYVc5dUlqb2lUa0VpZlN3aWJHOWphMTl2Y21SbGNsOTNhR1Z1WDNCaGFXUWlPbVpoYkhObExDSmxlSFJ5WVNJNmUzMHNJbk5wYm1kc1pWOXdZWGx0Wlc1MFgyRjBkR1Z0Y0hRaU9tWmhiSE5sTENKd2JXdGZhWEFpT2lJME5DNHlNRFF1TnpndU1UQTRJbjAud1Nwd3d6ZFQzXzNlNVJfX0NvTDVwSkE2dlJoeGhYc05fMFZGREQ5TmQ4TUZUb2Y3V0VKNzhLbXdEWWtaSHhhb2dPa3hCaU5McEdxU0dlN3RKcGlmaFE=']</value>
      <webElementGuid>6c0ea3dd-c28a-4ff7-9894-a361f6f1384e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
