<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check Installment Plans_expiry</name>
   <tag></tag>
   <elementGuidId>2d6fc964-8630-4e4a-81a5-05208b708973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mmyy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mmyy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baf04857-cf78-4f6c-a0fd-1932b6df60b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>caa2fe83-81b8-479d-82c0-a70f25f6a36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>update_two_hidden_fields();</value>
      <webElementGuid>01b8eab8-72d5-4a3e-b1d6-a71d3e0d5571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>90ce4d8e-cd39-46a2-b90f-e03690993c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>572d3c88-7519-414f-a4f9-6a8aa4ba743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mmyy</value>
      <webElementGuid>bc8579ed-30f0-4a80-9770-043102122adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mmyy&quot;)</value>
      <webElementGuid>b068805e-c62f-48b3-b3c1-9812b8a1c65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/checkOut_visa/Page_Aidd-Tools/iframe</value>
      <webElementGuid>6d7546cc-89af-4e8d-826e-358c6bd04b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mmyy']</value>
      <webElementGuid>104e3823-682e-4004-9690-bb8a8a339019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymob_checkout']/div[4]/input</value>
      <webElementGuid>4bc9086b-e243-4b0f-b754-d94413467d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ba47b730-3fbd-4bd9-af63-63aec19a3d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'MM/YY' and @type = 'tel' and @name = 'expiry' and @id = 'mmyy']</value>
      <webElementGuid>779b2459-3c28-4cca-ac8b-85c28b73ebdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
